### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/top.json?

### ISSUE THREAD

**Issue by agdamsbo** [redlib-org/redlib#246] opened 2024-09-18 07:14 UTC
## Describe the bug
  Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/top.json?&raw_json=1&geo_filter=GLOBAL

## Steps to reproduce the bug

1. Go to 'Popular'
2. Click on 'Top'
3. See error

## What's the expected behavior?
I would expect to see the relevant sorting. Same error occurs if I try to open comments or searching for any sub-reddits.

**Comment by Wawan61** [comment] 2024-09-18 08:54
What Happened to error why?

**Comment by Wawan61** [comment] 2024-09-18 09:09
Bug

**Comment by dchakro** [comment] 2024-09-18 11:54
I'm getting the same errors:

Failed to parse page JSON data

<img width="1240" alt="Screenshot 2024-09-18 at 4 54 10 AM" src="https://github.com/user-attachments/assets/63f758f0-c976-4123-8e95-32c3e3b34ae2">

**Comment by sigaloid** [comment] 2024-09-18 12:05
Dupe of #229

**Closed by sigaloid** 2024-09-18 12:05 UTC
Labels: bug
