### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 [RATE LIMITS]

### ISSUE THREAD

**Issue by arch-btw** [redlib-org/redlib#229] opened 2024-09-16 18:28 UTC
## Describe the bug

This error is currently being displayed on all instances.

## Steps to reproduce the bug

Go to any instance and it will say:

```Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL```

## What's the expected behavior?

To display any Reddit page.

## Additional context / screenshot

This started happening about 10 minutes ago.
The json file itself is still accessible by browser, so maybe the structure changed?

**Comment by khan5ula** [comment] 2024-09-16 18:41
Also experiencing this suddenly.

**Comment by netrunnereve** [comment] 2024-09-16 19:01
I'm seeing this as well on my own instance and on public instances. I tried restarting Redlib but it didn't help.

**Comment by cyhyraethz** [comment] 2024-09-16 19:03
I've also been experiencing this on my own instance. Restarting did seem to fix it, although I'm not sure if it will last.

**Comment by r7l** [comment] 2024-09-16 19:20
Same here. But i can call the JSON manually and get a normal response with JSON being returned. Not sure if the JSON itself has changed.

**Comment by sigaloid** [comment] 2024-09-16 19:26
Investigating this

**Comment by sigaloid** [comment] 2024-09-16 19:34
Is anyone reproducing this locally (not on a public instance)? Or does this require heavy load to trigger?

**Comment by netrunnereve** [comment] 2024-09-16 19:41
> Is anyone reproducing this locally (not on a public instance)? Or does this require heavy load to trigger?

This is happening on my local instance where I'm the only user.

**Comment by babeuh** [comment] 2024-09-16 19:42
> Is anyone reproducing this locally (not on a public instance)? Or does this require heavy load to trigger?

Happening on my single user instance which doesn't have much load at all.

**Comment by SteffenBauer** [comment] 2024-09-16 19:48
Also on my local home server, with only two people accessing it via local network.

Additional information: I run redlib as a systemd user service. Restarting the service makes redlib working again for a few minutes, after some minutes again above JSON error. I restarted the service several times, so far reproducible makes redlib always working again for a short time.

**Comment by Mr3ase** [comment] 2024-09-16 19:49
Same, on my own instance where I am the only user, and restarting/redeploying from the source image does fix it for a little while, though I am not sure if it lasts for a given duration or a given number of requests.
Also when checking the container logs every JSON error thing is paired with a 403 forbidden from reddit.

**Comment by r7l** [comment] 2024-09-16 20:04
Single user here as well. Mine is running on a VPS but i've just tried it locally and it's the same. It works for like 2 or 3 pages and then it breakes until restarted.

**Comment by sigaloid** [comment] 2024-09-16 20:14
I've narrowed it down to a network policy error that Reddit's picking up on. This causes a 403 (which we didn't special case previously) and this network violation is detectable via the `retry-after` header (and various other headers, plus plaintext response, but headers will be fastest). 

Going to push out a quick fix to catch the error, refresh the token, and avoid poisoning the cache. You may need to reload the page if you see this error, but it'll ideally be fixed right after. 

Would appreciate someone pulling the latest code and testing when this goes in. Docker image will be updated in a few minutes.

**Comment by sigaloid** [comment] 2024-09-16 20:17
Leaving open until I get confirmation that you don't see this error repeatedly. It may be spurious but that's the nature of the new (?) server behavior. Future improvements would include a default retry mechanism post-token-refresh but for now, if the issue goes away after a reload, I'm happy

**Comment by stoopkidddd** [comment] 2024-09-16 20:24
@sigaloid not entirely related, but might want to look at the failing docker build action, otherwise this fix isn't going to make it out to everyone

**Comment by sigaloid** [comment] 2024-09-16 20:30
Done, thanks!

**Comment by stoopkidddd** [comment] 2024-09-16 20:31
Thank you for the quick fix 🙏

**Comment by r7l** [comment] 2024-09-16 20:32
Thanks allot! If this fix works, could you drop a new release?

**Comment by edgar-vincent** [comment] 2024-09-16 20:38
The latest Docker image works for me. Thank you so much for the speedy fix!

**Comment by sigaloid** [comment] 2024-09-16 20:47
Weird that it works. since the container build is still failing: https://github.com/redlib-org/redlib/actions/runs/10891683866

Gonna be a small fix to get a new container built from `main` - just some fixing of the filenames. I have class right now, if someone could look at `.github/workflows/main-docker.yml:79` and see my recent commit (https://github.com/redlib-org/redlib/commit/118708400ad37c5ddfb8d54566d429c0f43b024a), and PR a fix, I could merge it. Else it'll probably be a few hours before I get to it.

**Comment by edgar-vincent** [comment] 2024-09-16 21:10
My bad, sorry about that. The error did disappear for a moment, so I thought it was because of a new build, but it is now back again.

**Comment by ButteredCats** [comment] 2024-09-16 22:08
The newest commit fixed the JSON errors, but I've just begun getting the `ERROR redlib::utils > Error page rendered: Couldn't send request to Reddit: Rate limit - try refreshing soon` error on both of my Redlib containers. After a restart of Redlib it only takes ~15 seconds to begin reappearing.

**Comment by HakaishinShwet** [comment] 2024-09-17 02:42
I have same thing to report that after latest commit we are getting new type of error which is
`Rate limit error`  

`Couldn't send request to Reddit: Rate limit - try refreshing soon | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL`

![20240917_08h06m42s_grim](https://github.com/user-attachments/assets/866d5917-8512-45ab-b62d-f35ed00bc94d)

**NOTE - I ALSO TRIED CLEANING COMPLETE CACHE WITH MY COOKIE MANAGER ADDON STILL SAME ISSUE :-))**

**Comment by wuchyi** [comment] 2024-09-17 07:57
> Weird that it works. since the container build is still failing: https://github.com/redlib-org/redlib/actions/runs/10891683866
> 
> Gonna be a small fix to get a new container built from `main` - just some fixing of the filenames. I have class right now, if someone could look at `.github/workflows/main-docker.yml:79` and see my recent commit ([1187084](https://github.com/redlib-org/redlib/commit/118708400ad37c5ddfb8d54566d429c0f43b024a)), and PR a fix, I could merge it. Else it'll probably be a few hours before I get to it.

I've submitted a PR #238, but to be frank, not entirely sure if it's what's required.

**Comment by master-hax** [comment] 2024-09-17 10:15
this issue is harder to mitigate since https://github.com/redlib-org/redlib/pull/59 was merged and we can no longer easily do a build in docker

**Comment by Tokarak** [comment] 2024-09-17 10:25
Please pin this issue, there is a slew of duplicates coming in

**Comment by Steinheausser** [comment] 2024-09-17 14:42
Hi, not sure if one more voice helps troubleshooting but I've just rebuilt and it fixed this issue. Am running it as an exe file on windows. However, this leads to issue #237.

**Comment by perennialtech** [comment] 2024-09-17 17:00
As @pimlie mentioned in https://github.com/redlib-org/redlib/pull/241#issuecomment-2355568510, restarting Redlib seems to temporarily resolve the rate limiting issue, and frequent restarts (intervals of <10 minutes) could act as a stopgap fix until a more permanent solution is found.

**Comment by CLKRUN** [comment] 2024-09-17 17:29
@perennialtech thanks, that helps for now.

**Comment by sigaloid** [comment] 2024-09-17 18:09
The new error is **intentional**. It's meant to provide a better error message. But, it's supposed to be fixed temporarily after that since it rolls over the token. So constantly restarting the container really shouldn't be necessary - if it is, my fix wasn't sufficient.

If anyone wants to do more investigation and provide more info, that would be much appreciated. I see the notifications rolling in but it's very difficult to find free time to go in-depth. I always try to provide enough information when I do my own bug fixes to allow others to understand how it works.

**Comment by wuchyi** [comment] 2024-09-17 18:31
I assume that since the currently-available still works intermittently, it is a new “feature” from Reddit’s side that we will have to bypass - not a “fix” per se.

**Comment by sigaloid** [comment] 2024-09-17 18:40
Docker container hasn't been updated to have the new "fix" (first error will still show but future ones should be fixed). Just merged #243 which should fix it. https://github.com/redlib-org/redlib/actions/runs/10909055320/job/30276427190

**Comment by LucifersCircle** [comment] 2024-09-17 18:48
> Docker container is now updated to contain the fix. Again, it really won't "fix" it, but it should reduce the number of reports since it rolls over the token immediately.

Working so far on my public instance, thank you!

**Comment by sigaloid** [comment] 2024-09-17 18:58
Yeah, I'm not sure if this is a permanent fix, since https://github.com/redlib-org/redlib/issues/229#issuecomment-2354114934 mentions even with the new fix, the error still occurs repeatedly. That means the error response from Reddit seems to be more frequent than I first thought. I need to do a deep dive on this and find out if it is rooted in some separate new rate limit, or if it's completely random (in which case token roll over won't fix it, a retry mechanism might, but it also might spam it, causing even more aggressive blocking?). I need to just collect a ton of statistics about it, how frequently it occurs, if a retry mechanism would avoid it, if it's per-token, etc. 

I worry that my "fix" wasn't a fix, it was just a glorified retry function.

**Comment by LucifersCircle** [comment] 2024-09-17 19:16
If there’s any info I can provide to help I’d love to, however the only thing I know for certain is it happens fast, and a container restart can mitigate it shortly.

**Comment by sigaloid** [comment] 2024-09-17 19:30
I think post-restart working is just a side effect. I think that it really just clears the cache and tries again. Whereas if you don't restart, but disable caching on the main `json` function and then retry, I think it'll work the second time. Next up is avoiding a poisoned cache value.

**Comment by thudeous** [comment] 2024-09-18 00:34
Just a datapoint: when this issue started happening yesterday, I replaced my private instance of redlib (docker arm) with the last version of libreddit (also docker arm) and that has been working just fine for the past day.  

So: whatever libreddit is doing to grab its data, does not seem to trigger this new Reddit error response.

P.S. Thanks so much for libreddit/redlib!

**Comment by argium** [comment] 2024-09-18 00:47
I loaded the homepage after restarting a container. Came back to it later and it was fudged. Assuming that it's not doing background work, that'd suggest a problem with caching. What, I'm not sure. I wouldn't expect redlin to hold onto anything for an extended period of time like this.

**Comment by sigaloid** [comment] 2024-09-18 12:06
It sounds like it's specifically a new serverside issue when requesting it from the oauth routes. If we request it normally, I'm not sure if it will give us the same ratelimit bypass as now, since it won't look like a device.

**Comment by mbestavros** [comment] 2024-09-18 14:00
> It sounds like it's specifically a new serverside issue when requesting it from the oauth routes. If we request it normally, I'm not sure if it will give us the same ratelimit bypass as now, since it won't look like a device.

Would it be at all feasible to allow server admins to pick which route they request from?

**Comment by sigaloid** [comment] 2024-09-18 14:23
Yeah absolutely, it would likely mean it's reverting to the standard routes' rate limits though, which are worse than OAuth. A retry system would probably be a better option since it really seems to be sporadic/random.

**Comment by aurtzy** [comment] 2024-09-18 14:55
Following @thudeous's discovery, I've done a git bisect which seems to point to 3bb5dc5f3e5221149f72b10ae8c2104a02d3a0ac as the likely first commit with this issue. In my testing, 3bb5dc5 exhibited the behavior within 5 minutes of starting, whereas none of my test runs of redlib on the parent commit 3592728 so far have shown any error message of this sort (one of which had it running for about 2 hours).

**Comment by sigaloid** [comment] 2024-09-18 15:21
Shocking. I could not tell you why that would be. But I can reproduce it and can confirm it's fixed. 

What I don't know is why. That's just a dep bump to `hyper-rustls` and matching patch to fix compilation. 

I see two possibilities:

* It could possibly be some fingerprinting that certain Reddit edge servers have deployed, and the older version of `hyper-rustls` doesn't have that issue. I suspect this is it since it **just** started happening without a corresponding source change.

* Or perhaps it's an issue with sporadic malformed HTTPS requests being generated by that version of `hyper-rustls`. It is 11 months old at this point and is outdated. But we can't upgrade it until we upgrade all of hyper, tokio, etc. Less likely but still possible and does still fit with the fact that it's a recent change - maybe certain Reddit edge servers have their HTTP parsing library updated to be more strict in what they accept, which would explain it happening all of a sudden.

Looking at `hyper-rustls` patch for that version, I don't see anything that jumps out at me. Maybe it's one of the dep bumps in _this diff_. https://github.com/rustls/hyper-rustls/compare/v%2F0.24.1...v%2F0.25.0

Either way, you just identified the issue. Thanks so much for bisecting, I didn't think to because I immediately assumed it was a serverside change exclusively so no code change could really cause it (barring the switched endpoints).

**Comment by sigaloid** [comment] 2024-09-18 15:29
Fixed in 793047f63f0f603e342c919bbfc469c7569276fa, new container is out on quay.io: https://github.com/redlib-org/redlib/actions/runs/10925300119

Going to fix a few other things before cutting a new release (such as failing tests). But for now, this issue is done. Thanks to everyone here who helped investigate, especially @aurtzy for finding the issue.

All instance operators should prioritize pulling the new image with at least commit 793047f.

**Closed by sigaloid** 2024-09-18 15:29 UTC
Labels: bug

**Comment by Tokarak** [comment] 2024-09-19 12:52
That's my commit 😍

**Comment by mirzaakdeniz** [comment] 2024-09-19 18:33
Ahoy mate, I think you updated for Docker, but not the main repo. I installed and running locally, by using:

git clone https://github.com/redlib-org/redlib && cd redlib
cargo run

code. Issue is continuing for me.

**Comment by sigaloid** [comment] 2024-09-19 18:39
Docker images are generated from the main repo. If you're seeing the rate limit issue still, it's more likely that it's an IP ban like in https://github.com/redlib-org/redlib/issues/217#issuecomment-2358837922. in which case there's not much that can be done

**Comment by r7l** [comment] 2024-09-19 21:45
Thanks allot for fixing the issue. Would it be possible to create a new release for those using releases to install Redlib?

**Comment by sigaloid** [comment] 2024-09-20 01:14
Yep, once I finish other things on my to do list like the failing tests

**Comment by BugZappa** [comment] 2024-09-20 15:48
Error is persistent for me. (private instance)

![image](https://github.com/user-attachments/assets/d978aa0d-1139-473a-9148-05c3c592a795)

![image](https://github.com/user-attachments/assets/41fc99c8-68a3-46b2-8f32-2f91bc2a3ad4)

**Comment by L-Be** [comment] 2024-09-20 17:32
@BugZappa Are you using a VPN by any chance? I had routed my local instance through a VPN using a Gluetun container and I was still getting the error. Once I switched to using the local network there have been no issues. I swapped it back to the VPN to test and got the error again shortly after. I think I was still being rate limited when using the VPN.

**Comment by sigaloid** [comment] 2024-09-20 18:09
@BugZappa you're running v0.31.0. Very old.

**Comment by BugZappa** [comment] 2024-09-20 18:16
> @BugZappa you're running v0.31.0. Very old.

Yeah for some reason Portainers "always pull image" feature sucks ass, so I did it through the CLI and got it now.

Thank you!

**Comment by maaaaz** [comment] 2024-09-30 23:30
Hello @sigaloid, thanks for your great work !

Any ETA for the release ?

**Comment by maaaaz** [comment] 2024-10-06 11:27
I see that some binaries of the v35.1 release (dating back 29th June) were updated 4 days ago: 
https://github.com/redlib-org/redlib/releases/tag/v0.35.1

Are these binaries fixing this issue? 
![image](https://github.com/user-attachments/assets/fdbbae42-e385-49f0-a3da-bf9783abf2f9)

**Comment by dave0003** [comment] 2024-10-06 12:39
I tried the redlib-x86_64-unknown-linux-musl version (that was updated 4 days ago) and it seems to be working, unlike the old v0.35.1 "redlib" version.

**Comment by stag-enterprises** [comment] 2024-10-30 19:42
I'm getting this issue again, using the second-latest commit.

**Comment by ButteredCats** [comment] 2024-10-30 20:40
Yep. Both my containers are running into it as well.

**Comment by bclouthier** [comment] 2024-10-30 21:28
I'm been getting this issue as well. Sometimes restarting my container gives me one page load.

**Comment by sigaloid** [comment] 2024-11-01 21:11
@drewbdoo #301 is the current rate limiting issue, but i can't reproduce it on the latest commit. are you sure you've updated to the latest commit?

**Comment by davralin** [comment] 2024-11-01 21:35
fwiw, everything works for me - on the latest commit.
Had some hicups yesterday, but all good today.

**Comment by drewbdoo** [comment] 2024-11-01 21:38
Thanks all - I was on the latest but from docker hub, not quay. Working now
