### ISSUE TITLE
🐛 Bug Report: Unable to Load 'Home' Feed on any instance as of today

### ISSUE THREAD

**Issue by VorpalQ** [redlib-org/redlib#115] opened 2024-05-29 21:36 UTC
As of around 16:00 EDT on 05/29/24, I am unable to load the 'Home' feed from any Redlib instance. I can load specific subreddits if I go directly to them (ex: /r/Android), and the  'All' or 'Popular' feeds, but the 'Home' feed with my subscriptions, etc generates the following error:

`Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve`

## Steps to reproduce the bug

1. Go to any Redlib instance.
2. Subscribe to one or more subreddits
3. Click the 'Feeds' dropdown by the redlib logo
4. Error occurs.

## What's the expected behavior?
  Prior to this, the 'Home' feed loaded properly with my subscriptions.

**Comment by sigaloid** [comment] 2024-05-29 22:10
on it!

**Comment by sigaloid** [comment] 2024-05-29 22:36
Done!

Transcript of live debugging log:

## Error

A URL like https://oauth.reddit.com/r/gaming+politics/hot.json?&raw_json=1 apparently redirects our client to reddit.com. but a regular curl of that seems to work just fine. 

Could be the mobile headers causing issues. 

* Try to write curl command exactly identical to request being made


??? - Curl can recreate it just fine? But Redlib running it does not work

-- investigate TLS profile - could *technically* be a change on their end but highly unlikely they'd just break multisubs


Main problem: Redirecting to https://reddit.com but we add REDDIT_BASE so we then do ` TRACE redlib::client > Requesting https://oauth.reddit.comhttps://www.reddit.com/?raw_json=1`

SUCCESS - the problem is a mobile user agent being added

`curl -X GET "https://oauth.reddit.com/r/gaming+politics/hot.json?&raw_json=1" -H "User-Agent: asdf"`

versus

`curl -X GET "https://oauth.reddit.com/r/gaming+politics/hot.json?&raw_json=1" -H "User-Agent: Reddit/Version 2022.26.0/Build 521193/Android 11" -v`

^^^


Hence, fix is to gate the user-agent to see if the request is a multi! 

In fact, it's as easy as removing the word Android. So I'm going to be quite evil indeed and insert a zero width space on these requests.

* Reasoning: If we simply strip the entire user agent on these requests, it opens us up to fingerprinting **all** of our traffic as evil and bad

* Solution: We include a zero width character that will bypass the `if request contains "Android` condition, yet not jump out to the naked eye :)

Try it out:

`curl -X GET "https://oauth.reddit.com/r/gaming+politics/hot.json?&raw_json=1" -H "User-Agent: Reddit/Version 2022.26.0/Build 521193/Android 11" -v`

In some editors like VSCode, this will show up blatantly as a zero width space along with a few other tricky unicode characters. Let's hope Reddit engineers don't review their logs in VSCode.

PR incoming!

**Comment by sigaloid** [comment] 2024-05-29 22:42
Fixed in https://github.com/redlib-org/redlib/commit/273d889f1b05b23ca1a038fd36da564289b6455a

**Closed by sigaloid** 2024-05-29 22:42 UTC
Labels: bug
