### ISSUE TITLE
🐛 Bug Report: Unable to view galleries if cross posted from other subreddit 

### ISSUE THREAD

**Issue by omnigenous** [redlib-org/redlib#216] opened 2024-09-05 22:51 UTC
## Describe the bug

Can't view gallery: https://www.reddit.com/r/hyprland/comments/1f6awfn/hyprland_catppuccin_all_the_wayyy_first_rice/ -> Click `/gallery...` -> "Nothing here"
Can view it just fine: https://www.reddit.com/r/unixporn/comments/1f69syr/hyprland_catppuccin_all_the_wayyy_first_rice/

## Expected behavior

Render gallery for cross posts and indicate that it was cross posted from other subreddit with a link to it. Or at least add url to original post instead of broken `/gallery...` link.

## Additional context / screenshot

![2024-09-05_22-46-50](https://github.com/user-attachments/assets/23bd4991-eb4a-41e8-9e7a-82242daa14fe)
![2024-09-05_22-46-58](https://github.com/user-attachments/assets/8bf45373-3b51-4438-a218-2b874c861121)

**Comment by sigaloid** [comment] 2024-09-06 20:55
Dupe of #195

**Closed by sigaloid** 2024-09-06 20:55 UTC
Labels: bug
