### ISSUE TITLE
🐛 Bug Report: Please fix the `latest` tag

### ISSUE THREAD

**Issue by C8opmBM** [redlib-org/redlib#132] opened 2024-06-02 07:52 UTC
## Describe the bug

As the title says, please point the latest tag to v 0.3.4
As of now, it's still on 3.1 which cannot be used.

Thank you.

**Comment by kevinsumner** [comment] 2024-06-02 16:48
This is a duplicate of #63, and relates to #122.

**Closed** 2024-06-02 22:17 UTC
Labels: bug
