### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1 | /r/popular/hot.json?

### ISSUE THREAD

**Issue by Lyzzydoesthings** [redlib-org/redlib#236] opened 2024-09-17 01:35 UTC
## Describe the bug

straight up just cant do anything, cant even open the website
##

**Comment by ketan-vijayvargiya** [comment] 2024-09-17 01:39
Likely a duplicate of: https://github.com/redlib-org/redlib/issues/229.

**Closed** 2024-09-17 18:09 UTC
Labels: bug
