### ISSUE TITLE
🐛 Bug Report: Couldn't send request to Reddit: Rate limit - try refreshing soon | /r/popular/hot.json?

### ISSUE THREAD

**Issue by DovletR** [redlib-org/redlib#240] opened 2024-09-17 08:45 UTC

**Comment by Tokarak** [comment] 2024-09-17 10:26
I'm getting this issue on main, with the fix for #229 merged. Many others mentioned the same issue on #229.

**Comment by Tokarak** [comment] 2024-09-17 10:27
Duplicate of #237.

**Closed** 2024-09-17 18:09 UTC
Labels: bug
