### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: EOF while parsing a value at line 1 column 0 | /r/popular/hot.json?

### ISSUE THREAD

**Issue by Fastball2880** [redlib-org/redlib#152] opened 2024-06-25 17:02 UTC
## Describe the bug
When going to any RedLib public instances, all of them will spit an error. Often times it will work when refreshing or coming back to any instances within an hour otherwise most of the time it won't work

## Steps to reproduce the bug

1. Go to 'any public instances available'

## What's the expected behavior?
Works as usual as it should, like using the official Reddit site

**Comment by redoomed1** [comment] 2024-06-25 17:11
Duplicate of #151

**Closed as not planned** 2024-06-25 17:37 UTC
Labels: bug
