### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1

### ISSUE THREAD

**Issue by anarqist** [redlib-org/redlib#230] opened 2024-09-16 18:36 UTC
## Describe the bug

No reddit link opens, all I get is: `Failed to parse page JSON data: expected value at line 1 column 1`

## Steps to reproduce the bug

1. Open a reddit link or open reddit directly.
2. Immediately the message appear: 
```
Failed to parse page JSON data: expected value at line 1 column 1 | /r/selfhosted/comments/1fiava0/selfhosted_document_signing/.json?&sort=new&raw_json=1
```
[Reddit link](https://www.reddit.com/r/selfhosted/comments/1fiava0/selfhosted_document_signing/)

3. It works one time if I reboot my Docker container but then the second time I will experience again the same issue.

Detailed error message in terminal:

```
2024-09-16 19:54:25 redlib  |  ERROR redlib::client > Got an invalid response from reddit expected value at line 1 column 1. Status code: 403 Forbidden
2024-09-16 19:54:25 redlib  |  ERROR redlib::utils  > Error page rendered: Failed to parse page JSON data: expected value at line 1 column 1 
2024-09-16 19:54:26 redlib  |  ERROR redlib::utils  > Error page rendered: Nothing here
```

## What's the expected behavior?

 Reddit website on my own redlib instance should open. 

## Additional context / screenshot

I am running redlib in Docker for Mac (ARM64)  containter on my own private network.

**Comment by griffi-gh** [comment] 2024-09-16 18:40
Duplicate of https://github.com/redlib-org/redlib/issues/229

**Closed** 2024-09-16 20:20 UTC
Labels: bug
