### ISSUE TITLE
🐛 Bug Report: Couldn't send request to Reddit: error trying to connect: dns error: failed to lookup address information: Name does not resolve

### ISSUE THREAD

**Issue by millionsofplayers** [redlib-org/redlib#117] opened 2024-05-30 05:27 UTC
## Describe the bug
  I can't use redlib because this error pops up instead of the front page

## Steps to reproduce the bug

1. Go to a redlib instance
2. get the error

## What's the expected behavior?

  To be able to see the front page

## Additional context / screenshot

  On other instances it works fine, but for some reason when I paste my preferences from one of the instances affected by this into a working one it makes the error happen there too

**Comment by millionsofplayers** [comment] 2024-05-30 05:58
Direct links to posts work (and subreddits too) it's just the front page I think

**Comment by rndmh3ro** [comment] 2024-05-30 06:43
Same here. What does help for me is clearing cache and cookies for redlib. Then the front page works again.

**Comment by millionsofplayers** [comment] 2024-05-30 06:48
It does work now, I'll have to resub to some subreddits though

**Comment by marcogiorgio** [comment] 2024-05-30 07:52
Same here, I cleared cache and cookies and it started working again. I re-subscribed to the subreddits I was inrerested in, reloaded the page and the problem happened again...

**Comment by dave0003** [comment] 2024-05-30 07:55
I was getting the same error on 0.31.0.  I just installed the latest 0.34.0, and it's working again without clearing cache or cookies.

**Comment by reterkha** [comment] 2024-05-30 09:56
I've cleared the cache and still getting the issue.

**Comment by lightr4in** [comment] 2024-05-30 11:53
> the problem seems only happened on home page when subscribe to 2+ subreddit (subscribe to a single sub doesn't cause this, nor does go to each sub separately)

Getting the same issue and checked the pihole logs to analyze the requested domain(s). 
The DNS resolution logs show two attempts to resolve domain `oauth.reddit.comhttps` with `3 (NXDOMAIN)` responses, which occur after successfully requesting the domain `oauth.reddit.com` (visiting Home Page)

This might be related. Has anyone observed similar behavior?

**Comment by 7LRX** [comment] 2024-05-30 17:50
The catsarch instance (@ v0.33) fixes the problem for me.

**Comment by millionsofplayers** [comment] 2024-05-30 20:39
Now I'm getting Failed to parse page JSON data: expected value at line 1 column 1 on posts and Failed to parse page JSON data: expected value at line 2 column 5 on subreddits

**Comment by Silvenga** [comment] 2024-05-30 20:44
@millionsofplayers see https://github.com/redlib-org/redlib/issues/118.

**Comment by sigaloid** [comment] 2024-05-30 22:10
This error was fixed in main by v0.33, closing!

**Comment by Iliageorgiev** [comment] 2024-06-18 18:28
Sadly this issue reappeared again .

**Comment by sigaloid** [comment] 2024-06-20 11:59
Please update to the latest docker container so you get the updated error page when you run into this error. I can't reproduce this especially not with more debug info.

See https://github.com/redlib-org/redlib/issues/131#issuecomment-2179316596

**Closed** 2024-06-25 23:52 UTC
Labels: bug

**Comment by sigaloid** [comment] 2024-06-25 23:53
Fixed! Sorry about the delay. Couldn't tell it was the multi sub causing this

**Comment by sigaloid** [comment] 2024-06-29 02:42
Weirdly this happens when you ask for some misformed requests but I added an additional more informative error page in 0f7eba717e5ec478ed4e78f7ba9e638b59962d42.
