### ISSUE TITLE
🐛 Bug Report: New posts not sorted by post creation time

### ISSUE THREAD

**Issue by hisel-sabermetrics** [redlib-org/redlib#161] opened 2024-06-28 09:30 UTC
## Describe the bug
The posts on "New" tab are not sorted by creation time

## Steps to reproduce the bug
1. Go to any subreddit
2. Click on New
3. Scroll down to load the posts

## What's the expected behavior?
The posts are sorted by span.created

## Additional context / screenshot
Here is a screenshot. The same happen on different instances.
![Screenshot](https://github.com/redlib-org/redlib/assets/96913686/903c735d-4006-4a9c-a35d-f99a63e06cc3)

**Comment by sigaloid** [comment] 2024-06-29 01:10
Can't reproduce.. What subreddit?

**Comment by sigaloid** [comment] 2024-06-29 15:28
Hm, that's the return order of the JSON from reddit, but not on the site. May be related to posts that were once removed but were then approved?

Nonetheless, pushed a fix out.

**Closed** 2024-06-29 15:48 UTC
Labels: bug
