### ISSUE TITLE
🐛 Bug Report: ERROR redlib::oauth > Failed to create OAuth client in Elapsed(()).

### ISSUE THREAD

**Issue by matheusroberson** [redlib-org/redlib#266] opened 2024-09-25 19:44 UTC
## Describe the bug
i'm selfhosting redlib with docker, when i try start container i see this error:

`redlib  |  ERROR redlib::oauth > Failed to create OAuth client in Elapsed(()). Retrying in 5 seconds...`

## Steps to reproduce the bug

1. Try start redlib container with docker
2. See error terminal

## Additional context / screenshot
I have technitium DNS server configured in docker, when i disable dns server redlib start

**Comment by sigaloid** [comment] 2024-09-25 19:56
Anything else within 5 seconds? Or is it constantly repeating?

If it repeats every 5 seconds, it's more than likely an IP ban.

**Comment by matheusroberson** [comment] 2024-09-26 10:04
Yes, it is constantly repeating. I don't know work an IP ban, but i can access Reddit in other devices and when i disable Technitium

**Comment by sigaloid** [comment] 2024-09-26 15:05
Any chance you can test Redlib specifically on a different IP?

**Comment by matheusroberson** [comment] 2024-09-26 16:02
Sorry, i can't test in a different IP and i meant in my last commentary, it is possible to access Redlib without my DNS server self-hosted

**Comment by sigaloid** [comment] 2024-09-26 19:05
I just pushed 6b44c1abf25f16b09a021bc423bbdca7e5f71cc7 which should additional logging to that function. Please run the program with `RUST_LOG=redlib=trace` and paste the full log output after a few tries.

**Comment by ButteredCats** [comment] 2024-09-26 23:06
Sorry to butt in but I think this is just related to Technitium's blocking function. Assuming that's setup, anyways. Seeing that it works when Technitium is off Redlib itself clearly functions fine.

 Just go into Settings > Blocking, disable "Enable Blocking" and save your settings. After that check if Redlib begins working.

Both of my containers running Redlib are using selfhosted Technitium DNS servers and it works fine, so I don't think this has anything to do with Redlib or any inherent problem with Technitium.

**Comment by sigaloid** [comment] 2024-09-27 00:46
Ugh I misread that part. Yeah, @matheusroberson you have something specifically set up to block Reddit requests. That's what's causing the issue. Closing for now unless you can reproduce without Technitium

**Closed by sigaloid** 2024-09-27 00:46 UTC
Labels: bug

**Comment by sigaloid** [comment] 2025-04-21 18:16
Please open a new issue with your exact log lines. I'm unable to reproduce this, but more importantly, if you really are having this *exact* problem, it's almost certainly a networking issue between the docker daemon and the internet. The exact error message here ("failed to create oauth client in Elapsed(())") means that no specific catchable error occurred, the signup flow just took 5 seconds to complete (normally <100ms). This means either Reddit is dropping requests (1. unlikely, as we still match well-formed application requests, and 2. not even returning some kind of error at ALL, just waiting for the timeout to elapse), or your networking stack has a problem (IPv6?).
