### ISSUE TITLE
Couldn't send request to Reddit: Rate limit - try refreshing soon

### ISSUE THREAD

**Issue by stemy2** [redlib-org/redlib#250] opened 2024-09-19 04:00 UTC
## Describe the bug

The message in the title is showed instead of the expected page.
## Steps to reproduce the bug

1. Go to any subreddit.

## What's the expected behavior?

The expected subreddit.

**Comment by sigaloid** [comment] 2024-09-19 17:14
Dupe of #229. Update the container

**Closed** 2024-09-19 17:14 UTC
Labels: bug
