### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by r2fo** [redlib-org/redlib#36] opened 2024-01-31 21:44 UTC
Hi,
I have setup an instance at https://redlib.r4fo.com and at http://redlib.r4focoma7gu2zdwwcjjad47ysxt634lg73sxmdbkdozanwqslho5ohyd.onion. Can you please add it to the list?

ISP: Netcup
Country: Germany
Cloudflare

**Comment by sigaloid** [comment] 2024-02-06 13:18
It looks like you're running Libreddit, not Redlib :)

**Comment by sigaloid** [comment] 2024-02-06 19:03
Oh :( that's a very weird thing to happen - Redlib doesn't do anything majorly different from Libreddit that would cause any proc mounts to be touched... Is this reproducible?

**Comment by sigaloid** [comment] 2024-02-12 18:47
Update: that's a seccomp issue (https://github.com/redlib-org/redlib/issues/34) and should be fixed by removing the seccomp rule in your compose.

**Closed as completed** 2024-02-19 17:59 UTC
