### ISSUE TITLE
🐛 Bug Report: Rate Limit error

### ISSUE THREAD

**Issue by SteffenBauer** [redlib-org/redlib#237] opened 2024-09-17 07:01 UTC
## Describe the bug
Redlib started to throw JSON parse errors since yesterday (#229), caused by 403 errors from reddit. Redlib was patched very quickly, but since then Rate Limit errors occur.
This is already reported in issue #229 , but I think as this is a new issue it makes sense to open a new bug report.

## Steps to reproduce the bug
* Install latest redlib commit (https://github.com/redlib-org/redlib/commit/8ef45456d696b254b0378b75ff4db0345d6bc217)
* Browse redlib for several minutes
* Observed: After some minutes, redlib starts to fail with Rate Limit error.
* Refreshing the page on browser does not change back, still throws rate limit error, even after waiting for some minutes.

## What's the expected behavior?
Redlib continues to show reddit content

## Additional context / screenshot
```
Couldn't send request to Reddit: Rate limit - try refreshing soon | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL
```
Message in systemd journal log:
```
Sep 17 08:55:26 hufflepuff redlib[1763]:  ERROR redlib::utils > Error page rendered: Couldn't send request to Reddit: Rate limit - try refreshing soon
```

**Comment by SteffenBauer** [comment] 2024-09-17 07:09
Additional information:

* Redlib works again for some minutes when redlib service is restarted.
* Refreshing the page in browser does not change the Rate Limit error, even after waiting for several minutes without any access to redlib in the mean time.
* Local build from source, running as systemd user service on local home server. Tested with only me accessing redlib, light load (rate limit error occurs after browsing a few dozen reddit pages)

**Comment by Tokarak** [comment] 2024-09-17 10:34
Exactly the same situation and experience.

**Comment by Tokarak** [comment] 2024-09-17 10:37
Relevant code:
https://github.com/redlib-org/redlib/blob/8ef45456d696b254b0378b75ff4db0345d6bc217/src/client.rs#L266-L270

**Comment by sigaloid** [comment] 2024-09-18 15:45
Closing as duplicate of #229

**Closed by sigaloid** 2024-09-18 15:45 UTC
Labels: bug
