### ISSUE TITLE
🐛 Bug Report: Image links in body of post all become the same link

### ISSUE THREAD

**Issue by ButteredCats** [redlib-org/redlib#48] opened 2024-02-08 22:57 UTC
## Describe the bug
When looking at a post that has multiple images in the body they will all become the same link instead of being the link to the image it was originally supposed to be on Reddit.

## Steps to reproduce the bug
1. Find a post that has multiple images in the body
2. Click on the post
3. Click on all the images and see that they're all the same
4. View the post on Reddit and see that they're not all supposed to be the same image

## What's the expected behavior?
The links will go to their respective image instead of all being transformed into the same one.

## Additional context / screenshot
https://redlib.catsarch.com/r/test/comments/d9hta9/test_multiple_images/ vs https://www.reddit.com/r/test/comments/d9hta9/test_multiple_images/
and
https://redlib.catsarch.com/r/homelab/comments/1albvin/so_this_is_a_before_and_after_before_fired_and/ vs https://www.reddit.com/r/homelab/comments/1albvin/so_this_is_a_before_and_after_before_fired_and/

**Comment by oifj34f34f** [comment] 2024-02-10 08:03
Duplicate of https://github.com/redlib-org/redlib/issues/25 (see section "Examples")

**Comment by ButteredCats** [comment] 2024-02-10 13:52
Ah, wasn't aware that one called out links in the post itself not embedding too, thought it was only comments.

It doesn't mention different picture links all becoming the same though. I'll edit this issue to just be about that instead.

**Closed** 2024-04-07 15:58 UTC
Labels: bug, help wanted
